version: '3.8'

services:
  loadbalancer:
    image: nginx:latest
    ports:
      - "80:80"
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    networks:
      - coursecompanion-network
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - coursecompanion-network
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        order: rolling-update
      rollback_config:
        parallelism: 1
        order: rollback
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=81
      - FIREBASE_DB_URL=https://coursecompanion-de8fa-default-rtdb.firebaseio.com/
    configs:
      - source: firebase_config
        target: /app/firebase-config.json
    networks:
      - coursecompanion-network
    deploy:
      replicas: 4
      update_config:
        parallelism: 1
        order: rolling-update
      rollback_config:
        parallelism: 1
        order: rollback
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:81/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  coursecompanion-network:
    driver: overlay

configs:
  nginx_config:
    file: ./nginx.conf
  firebase_config:
    file: ./firebase-config.json